[package]
name = "redgem"
version = "0.1.0"
license = "AGPL-3.0-or-later"
edition = "2024"

[dependencies]
ada-url = "=3.2.3"
clap = { version = "4.5.38", default-features = false, features = ["derive", "std", "help", "usage"] }
foxerror = "0.1.1"
